apiVersion: v1
kind: Secret 
metadata:
  name: leetcode-Secret
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: "1658"
  POSTGRES_URL: postgresql://postgres:1658@leetcode-postgres:5432/leetcode_tracker