SELECT * FROM "problems";
SELECT * FROM "Users";
SELECT * FROM "Notification";
DROP TABLE problems;
TRUNCATE TABLE "Users" RESTART IDENTITY CASCADE;
DROP TABLE "Users" CASCADE;
DROP TABLE "Notification" CASCADE;


